---
- name: OMNI SETUP INITIALIZATION
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: Setup for MacOSX with apple silicon chip
      when: ansible_distribution == "MacOSX" and ansible_architecture == "arm64"
      block:
        - name: Detect mac essentials dev tools
          block:
            - name: Detect if xcode commands are installed
              ansible.builtin.command: "xcode-select --version"
              register: xcode
              changed_when: xcode != 0

            - name: Detect if brew is installed
              ansible.builtin.command: "brew --version"
              register: homebrew
              changed_when: homebrew != 0
              ignore_errors: true

        - name: Detect if mas is installed
          ansible.builtin.command: "mas version"
          register: mas
          changed_when: mas != 0
          ignore_errors: true

        - name: Install packages via BREW
          community.general.homebrew:
            name: "{{ item }}"
            state: absent
          loop: "{{ homebrew_packages }}"

        - name: Install programs via mas
          community.general.mas:
            id:
              - 571213070 # installation of davinci Resolve
            state: present

        - name: Set dock settings for MacOSX
          become: true
          block:
            - name: Detect if show-apps-in-docs is enabled
              ansible.builtin.command: "defaults read com.apple.dock show-apps-in-dock"
              register: is_show_apps_in_dock
              changed_when: is_show_apps_in_dock != 1

            - name: Set show-apps-in-dock as false
              when: is_show_apps_in_dock != 0
              ansible.builtin.command: "defaults write com.apple.dock show-apps-in-dock -bool False"
              changed_when: is_show_apps_in_dock == 1

            - name: Detect if show-recents is enabled
              ansible.builtin.command: "defaults read com.apple.dock show-recents"
              register: is_show_recents
              changed_when: is_show_recents != 1

            - name: Set show-apps-in-dock as false
              when: is_show_recents != 0
              ansible.builtin.command: "defaults write com.apple.dock show-recents -bool False"
              changed_when: is_show_recents == 1
