---
- name: SETUP INITIALIZATION
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: Setup for MacOSX with apple silicon chip
      when: ansible_distribution == "MacOSX" and ansible_architecture == "arm64"
      block:
        - name: Set settings for MacOSX
          block:
            - name: Install homebrew and apps
              ansible.builtin.import_role:
                name: geerlingguy.mac.homebrew
                tasks_from: main.yml

            - name: Install mas and apps
              ansible.builtin.import_role:
                name: geerlingguy.mac.mas
                tasks_from: main.yml

            - name: manage dock and apps
              ansible.builtin.import_role:
                name: geerlingguy.mac.dock
                tasks_from: main.yml

        - name: Set development settings
          become: true
          become_method: ansible.builtin.sudo
          block:
            - name: Copy zshrc file
              ansible.builtin.copy:
                src: ./files/.zshrc
                dest: "~/.zshrc"
                mode: "0644"
                force: true
                # remote_src: false

            - name: Copy vimrc file
              ansible.builtin.copy:
                src: ./files/.vimrc
                dest: "~/.vimrc"
                mode: "0644"
                force: true
                # remote_src: false

            - name: Render gitconfig file
              ansible.builtin.template:
                src: gitconfig.j2
                dest: ~/.gitconfig
                mode: '0644'

        - name: Run finisher script # noqa no-changed-when
          ansible.builtin.command: "./files/.osx"